// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lhs_sample_cpp
Rcpp::NumericMatrix lhs_sample_cpp(int n, int k);
RcppExport SEXP _degen_lhs_sample_cpp(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(lhs_sample_cpp(n, k));
    return rcpp_result_gen;
END_RCPP
}
// random_sample_cpp
Rcpp::NumericMatrix random_sample_cpp(int n, int k);
RcppExport SEXP _degen_random_sample_cpp(SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(random_sample_cpp(n, k));
    return rcpp_result_gen;
END_RCPP
}
// sample_par_space_cpp
Rcpp::NumericMatrix sample_par_space_cpp(Rcpp::NumericVector lower, Rcpp::NumericVector upper, int n, bool lhs);
RcppExport SEXP _degen_sample_par_space_cpp(SEXP lowerSEXP, SEXP upperSEXP, SEXP nSEXP, SEXP lhsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type lhs(lhsSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_par_space_cpp(lower, upper, n, lhs));
    return rcpp_result_gen;
END_RCPP
}
// effective_bounds_cpp
Rcpp::NumericVector effective_bounds_cpp(double lower, double upper, double scale);
RcppExport SEXP _degen_effective_bounds_cpp(SEXP lowerSEXP, SEXP upperSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(effective_bounds_cpp(lower, upper, scale));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_degen_lhs_sample_cpp", (DL_FUNC) &_degen_lhs_sample_cpp, 2},
    {"_degen_random_sample_cpp", (DL_FUNC) &_degen_random_sample_cpp, 2},
    {"_degen_sample_par_space_cpp", (DL_FUNC) &_degen_sample_par_space_cpp, 4},
    {"_degen_effective_bounds_cpp", (DL_FUNC) &_degen_effective_bounds_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_degen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
