# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.lhs_sample_cpp <- function(n, k) {
    .Call(`_degen_lhs_sample_cpp`, n, k)
}

.random_sample_cpp <- function(n, k) {
    .Call(`_degen_random_sample_cpp`, n, k)
}

.sample_par_space_cpp <- function(lower, upper, n, lhs) {
    .Call(`_degen_sample_par_space_cpp`, lower, upper, n, lhs)
}

.effective_bounds_cpp <- function(lower, upper, scale = 10.0) {
    .Call(`_degen_effective_bounds_cpp`, lower, upper, scale)
}

